module.exports = {
  COM_ENTRY: 'COM_ENTRY',
  COM_RESET: 'COM_RESET',
  LOG_RESET: 'LOG_RESET',
  SL_RESET: 'SL_RESET',
  TABLE_RESET: 'TABLE_RESET',
  TABLE_ENTRY: 'TABLE_RESET',
  ERROR_OCCURRED: 'ERROR_OCCURRED',
};